### ISSUE TITLE
Lassen Tapeout Task List

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#98]
Resolving/Missing Features
- [x] Counter - dropping
- [x] Breakpoints/IRQ - Not dropping
- [x] Floating Point Comparison/flags, Ross, Nikhil
- [x] Resolve differences between python gmpy2.mpfr implementation and design ware, Caleb, Ross, Nikhil
- [x] clk_en/Register Valid
- [x] Carry in
- [x] compare specification of instructions to both python simulator and RTL, Lenny, Keyi

Missing randomized Tests
- [x] "micro" FP ops, Nikhil, Ross (branch 'float-test')
  - [x] GetMant
  - [x] AddIExp
  - [x] SubExp
  - [x] CnvExp2F
  - [x] GetFInt
  - [x] GetFFrac
  - [x] FCnvInt2F
  - [x] FPSub
  - [x] FPAdd
- [ ] Complex Ops, Nikhil, Ross (Branch 'complex-float')
  - [x] div
  - [x] ln
  - [x] exp
  - [ ] round
  - [ ] Ceil
  - [ ] Floor
- [x] Register Modes (for each of the 5 inputs), Pat:
  - [x] Delay
  - [x] Const
  - [x] Bypass
- [x] Carry tests, Ross ('add32' -> master)
  - [x] adc
  - [x] sbc
  - [x] add32 (complex op)
  - [x] sub32 (complex op)
- [x] IRQ

- [x] Reading and writing Data and bit registers (Ross/Keyi)
- [x] Stall

- [x] Asynchronous reset on Data/Bit Registers (Lenny)
  - magma PR: https://github.com/phanrahan/magma/pull/412
  - lassen PR: https://github.com/StanfordAHA/lassen/pull/124

RTL
- [x] Check that no functional units are duplicated, Lenny
  - [x] check that FP FUs are not duplicated (only one instance of add/mul modules in output verilog)
  - [x] reduced the number of multiply units via https://github.com/StanfordAHA/lassen/pull/131 and https://github.com/StanfordAHA/lassen/pull/132
- [x] Sanity check the RTL and look for simple optimizations, Lenny
  - [x] Register (Peak) - visually inspected and tested via https://github.com/phanrahan/peak/pull/56
  - [x] RegisterMode - https://github.com/StanfordAHA/lassen/pull/125
  - [x] These datapath elements are currently tested through `test_pe` so we're fairly confident in there functionality:
    - _lut
    - adc
    - alu
    - cond
    - ite
    - lut
    - overflow
    - PE

**Comment by steveri** [comment]
Do we have tests for comparison opa (gt, ge, lt, le, eq, neq)? This is still an unchecked (May 15) goal (https://github.com/StanfordAHA/Private/blob/master/goals/unified_goals.md).

**Comment by steveri** [comment]
Should FPAdd, FPSub tests be on this task list? I notice it is still an open issue https://github.com/StanfordAHA/lassen/issues/42

**Comment by phanrahan** [comment]
The register VALID mode is not implemented. Can we remove that test?
